### ISSUE TITLE
Calendar not showing correctly with onPush change detection

### ISSUE THREAD

**Issue by gentle9** [kekeh/angular-mydatepicker#13]
Hi,
the Calendar doesn´t popup correctly when the component that contains the input component has set the changeDetection to onPush.

Here is a example where you can see the difference.
https://stackblitz.com/edit/angular-emptyproject-8-pipe-y33hq2

**Comment by tomastalian** [comment]
Hi @gentle9 , 
i have same problem and this is my workaround:
call
` this.changeDetectorRef.detectChanges(); `
after 
`dp.toggleCalendar();`

Here is your example with this fix. 
https://stackblitz.com/edit/angular-emptyproject-8-pipe-mj1xuj

**Comment by kekeh** [comment]
Hello @gentle9  and @tomastalian 

Here is working example: https://stackblitz.com/edit/angular-emptyproject-8-pipe-nxavs3?file=src%2Fapp%2Fcalendar.component.ts
