### ISSUE TITLE
Unable to position the calendar in desired position of the window 

### ISSUE THREAD

**Issue by sanjeevjeeva17** [kekeh/angular-mydatepicker#15]
I wanted to display the calendar above the text input box, and hence forth unable to override the style **top** property.

**Comment by sanjeevjeeva17** [comment]
I made openSelectorTopOfInput : true, and it works

**Comment by zipporaSay** [comment]
not working for me

**Comment by kekeh** [comment]
Try option appendSelectorToBody: true
