### ISSUE TITLE
prevent typing in input filed

### ISSUE THREAD

**Issue by krishnaGmail** [kekeh/angular-mydatepicker#17]
Hello Sir, 

Your plugin is working well for me. Thanks to that.
But when I try to type a text in the input field of an angular-mydatepicker directive it is enabled to typing there. Plz, help me out how to prevent typing text in angular-mydatepicker.

Thank You

**Comment by kekeh** [comment]
You can set input box disabled or readonly.

```html
<input angular-mydatepicker disabled />
or
<input angular-mydatepicker readonly />
```

**Comment by krishnaGmail** [comment]
Sir really appreciate your help. Thank you.

**Comment by kekeh** [comment]
If you are using version **0.2.1** you can also use **div** as a host element. Then the date field is not editable.

See example code from here: https://github.com/kekeh/angular-mydatepicker/tree/master/example/app/date-picker-div-host-element

Check also the **divHostElement** option from the README.

**Comment by 9marta5** [comment]
Hi, if I set input box disabled, the value of the angualr-mydatepicker is doesn't show.
My input box is like this:
```
<input class="input-box" angular-mydatepicker
                                    (dateChanged)="onDateChange($event,row,allColumns[i])" name="mydate"
                                    [locale]="locale" (click)="dp.toggleCalendar()" [(ngModel)]="row[0].DateContent"
                                    [ngModelOptions]="{standalone: true}" #dp="angular-mydatepicker"
                                    autocomplete="off" [disabled]="!allColumns[i].colDef.Editable" />
```

**Comment by kekeh** [comment]
Hi @9marta5 

You can try to do it this way:
```ts
public disabled: boolean = true;
```
```html
<input name="mydate" [attr.disabled]="disabled ? '' : null" />
```
In above if the value of the **disabled** member is true then there will be **disabled** attribute in the input box, otherwise not.

I have done it that way here https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-ngmodel/date-picker-ngmodel.html#L282 in my test application and it works.

**Comment by 9marta5** [comment]
Hi @kekeh thank you so much. It works!

**Comment by sofianekorbi** [comment]
> Hi @9marta5
> 
> You can try to do it this way:
> 
> ```ts
> public disabled: boolean = true;
> ```
> 
> ```
> <input name="mydate" [attr.disabled]="disabled ? '' : null" />
> ```
> 
> In above if the value of the **disabled** member is true then there will be **disabled** attribute in the input box, otherwise not.
> 
> I have done it that way [here](https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-ngmodel/date-picker-ngmodel.html#L282) in my test application and it works.
> 
> [Here](https://github.com/kekeh/angular-mydatepicker#development-of-this-component) is instructions on how to run the test application.

Thanks for the trick !
