### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by igormap42** [kekeh/angular-mydatepicker#18]
Is it possible to add an RTL (right to left) support to the calendar?
Here is an example how it should look like (mostly problem is only in arrows)
![Annotation 2019-10-06 093744](https://user-images.githubusercontent.com/20061166/66265387-280b4180-e81e-11e9-9066-a5c59434045c.jpg)

**Comment by kekeh** [comment]
I have added **RTL** support.  Can you try version **0.4.1**.

There is option **rtl: true | false**
