### ISSUE TITLE
Using with Angular AOT and Inernet Explorer

### ISSUE THREAD

**Issue by gunnarsireus** [kekeh/angular-mydatepicker#19]
Hello. I'm trying to use angular-mydatepicker with Angular AOT compiler and Internet Explorer. I think the problem is that IE doesn't support the spread operator or the destructuring assignments. However, without AOT angular-mydatepicker works perfectly but with AOT on Internet Explorer I get ERROR TypeError: Ett objekt förväntas. (An object was expcted). I have tried to use babel-loader but it didn't help.

**Comment by kekeh** [comment]
Probably you have to add **polyfills** to your project.

This project https://github.com/kekeh/angular-mydatepicker/tree/gh-pages works with **IE11**.
Same project online https://kekeh.github.io/angular-mydatepicker/
