### ISSUE TITLE
angular Ivy 

### ISSUE THREAD

**Issue by sysmat** [kekeh/angular-mydatepicker#20]
When using angular 8 and enabling Ivy compiler date picker popup is miss shaped.

![datepickerMissShaped](https://user-images.githubusercontent.com/69830/68300465-1b3c7080-009e-11ea-8a0e-45aab2ac01c1.png)

When disabling Ivy compiler it look ok(the same code)

![datepickerOk](https://user-images.githubusercontent.com/69830/68300730-a61d6b00-009e-11ea-8623-7b7cb270d40c.png)

**Comment by kekeh** [comment]
I did fix. You can try version 0.2.0.
