### ISSUE TITLE
Switching the year and month individualy

### ISSUE THREAD

**Issue by jruescher** [kekeh/angular-mydatepicker#25]
hi,
is it possible to switch the year and month (in the calendar header) individualy?
It was available in the older version [https://kekeh.github.io/mydatepicker/](url)
![old-version](https://user-images.githubusercontent.com/14200928/73361323-08a09480-42a5-11ea-8f17-7cf8033ab9d1.png)

**Comment by kekeh** [comment]
You can switch to the month view to click a **month name** on the header. Same works also with a **year**. There are also options to these:

**monthSelector** - If **true** and if month label is selected opens a selector of months.
**yearSelector** - If **true** and if year label is selected opens a selector of years.

Was that the answer to your question?

**Comment by jruescher** [comment]
hey,
thanks for the reply.
Not excactly.. i want to switch the year with the Arrow Symbol.
So for example:

< Jan > .. < 2021>
< Jan > .. < 2022> 

It was working like this in the old version

**Comment by kekeh** [comment]
In this component by clicking the arrow symbol change only month. 

I have changed that functionality in this new component, because almost all date pickers work that way. Why you need to change the year by clicking the arrow button?

**Comment by kekeh** [comment]
If you quickly want to change a year, you have to click a year number on header and select a year you want.
