### ISSUE TITLE
angular 9

### ISSUE THREAD

**Issue by naren7229** [kekeh/angular-mydatepicker#26]
Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/core" (requires "^7.2.0" (extended), would install "9.0.0").
                  Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/common" (requires "^7.2.0" (extended), would install "9.0.0").

**Comment by kekeh** [comment]
Hello @naren7229 

Try the latest version **0.3.8**.
