### ISSUE TITLE
required directive is no work

### ISSUE THREAD

**Issue by coloz** [kekeh/angular-mydatepicker#28]
in ngForm,add required directive, the mydatepicker always shows ng-invalid class

```
            <input class="date-input" placeholder="点击选择时间" angular-mydatepicker name="date"
                (click)="dp.toggleCalendar()" [locale]="'zh-cn'" [(ngModel)]="date" [options]="myDpOptions"
                #dp="angular-mydatepicker" (dateChanged)="onDateChanged($event)" required />
```

**Comment by kekeh** [comment]
I tested with this https://github.com/kekeh/angular-mydatepicker/tree/master/example/app/date-picker-ngmodel component and it worked ok. That component belongs to the example application.

**No date selected => ng-invalid**
![invalid](https://user-images.githubusercontent.com/11028839/74587204-64368600-4ff8-11ea-8c5d-26c1de29cd83.png)

**Date selected => ng-valid**
![valid](https://user-images.githubusercontent.com/11028839/74587209-70224800-4ff8-11ea-80f7-e36fc3d205e0.png)

Here https://github.com/kekeh/angular-mydatepicker#development-of-this-component are instructions on how to run test application.

Before run the application add the **required** attribute to this line https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-ngmodel/date-picker-ngmodel.html#L271

Then you can test the case.
