### ISSUE TITLE
CalendarComponent: Object is possibly 'undefined' on 0.4.4

### ISSUE THREAD

**Issue by aleksandar-kandzhichki** [kekeh/angular-mydatepicker#31]
Hello, while building angular project with strict null type checks, I am getting the following error:
![image](https://user-images.githubusercontent.com/13217235/75673283-4705e680-5c8b-11ea-9543-ca247d11f04f.png)

Issue comes from here: https://github.com/kekeh/angular-mydatepicker/blob/84ec9f07f904e4c7977f9f171eeff5a4dbedf5b0/projects/angular-mydatepicker/src/lib/components/calendar/calendar.component.html#L2

In the interface for options it says styles are nullable, so in the calendar component there should be check if they exist - or make sure they exist
https://github.com/kekeh/angular-mydatepicker/blob/84ec9f07f904e4c7977f9f171eeff5a4dbedf5b0/projects/angular-mydatepicker/src/lib/interfaces/my-options.interface.ts#L57

**Comment by kekeh** [comment]
Actually it shouldn't be **undefined**. The value comes from here: https://github.com/kekeh/angular-mydatepicker/blob/84ec9f07f904e4c7977f9f171eeff5a4dbedf5b0/projects/angular-mydatepicker/src/lib/services/angular-mydatepicker.config.service.ts#L53

The default config values are read here: https://github.com/kekeh/angular-mydatepicker/blob/84ec9f07f904e4c7977f9f171eeff5a4dbedf5b0/projects/angular-mydatepicker/src/lib/angular-mydatepicker.input.ts#L70

**Comment by aleksandar-kandzhichki** [comment]
@kekeh  I see, but it is still issue with the types - in the type you say it is possibly undefined, so when using it it would guess you might not have it
![image](https://user-images.githubusercontent.com/13217235/75680180-abc83d80-5c99-11ea-906c-e3d7b4a47e1e.png)

(this produces error with strictNullChecks: true in TsConfig)
Maybe there should be added an `!` to assert TS that it will be there?:  
![image](https://user-images.githubusercontent.com/13217235/75680217-c69ab200-5c99-11ea-8868-0c2cd767a673.png)

**Comment by kekeh** [comment]
Ok. I will check that soon.

**Comment by aleksandar-kandzhichki** [comment]
I can give you a stackblitz with reproduction if needed, but basically adding it in the tsconfig should reproduce the error. I forked the project and fixed it there for me, so it is building properly now, but still would be good to be included here :)

**Comment by kekeh** [comment]
How you fix it?

**Comment by aleksandar-kandzhichki** [comment]
https://github.com/aleksandar-kandzhichki/angular-mydatepicker/commit/98284778439434d608e222956f718ccb94ed16ac

I personally prefer this approach - where you make sure even if it is undefined, you would add some valid value there.

The other option is what I showed in the picture - add `!` after the `stylesData` so you assure TS that the property will not be undefined

**Comment by kekeh** [comment]
Looks good. I am happy if you can create a pull request from this change :-)

**Comment by kekeh** [comment]
Fixed in version **0.4.5**.
