### ISSUE TITLE
When disableUntil date is higher than the ngModel date, the date will not show

### ISSUE THREAD

**Issue by STheFox** [kekeh/angular-mydatepicker#34]
Hi,

When a date is initialized by using ngModel to let's say 14/05/2019, and the disableUntil is set to 01/01/2020, the date will not be shown. In the previous version of the datepicker (mydatepicker), the date would still be shown.

I created a stackblitz where you can simulate the issue. https://stackblitz.com/edit/angular-9-1-0-angular-mydatepicker

The previous approach seemed to me to be better in user experience. As it is now, it doesn't seem like a value was initialized.

Thanks.

**Comment by kekeh** [comment]
Hi @STheFox 

I fixed this issue. Install new version **0.5.4**.

**Comment by STheFox** [comment]
@kekeh  Thanks! I can confirm this issue is fixed on the new version.
