### ISSUE TITLE
Difference between angular-mydatepicker and mydatepicker?

### ISSUE THREAD

**Issue by be-ndee** [kekeh/angular-mydatepicker#35]
Hello, thanks for the cool date picker! At the moment I use the ngx-mydatepicker library. But I wanted to switch to the newer one, to support the newer angular versions.

I noticed that in the angular-mydatepicker library, the todayNextBtn option is not available anymore. But in mydatepicker it is available.

Could you tell me the differences between angular-mydatepicker and mydatepicker or why you created both of these two libraries? Would be good to know, thank you! :-)

**Comment by kekeh** [comment]
Hi @be-ndee 

angular-mydatepicker 
=================
- is more configurable
- has more features
- it based on newer Angular version
- it is implemented as a directive 
- input box is your own code
- it based on ngx-mydatepicker library

You can also read this: https://github.com/kekeh/angular-mydatepicker#main-features

**Comment by be-ndee** [comment]
Thank you for the fast reply! But the "today" button is not possible anymore, right?

**Comment by STheFox** [comment]
> Thank you for the fast reply! But the "today" button is not possible anymore, right?

@be-ndee I can confirm the 'today' button is not available anymore.

**Comment by be-ndee** [comment]
Thanks both of you! :-)
