### ISSUE TITLE
dd/mm as dateFormat option gives errors

### ISSUE THREAD

**Issue by STheFox** [kekeh/angular-mydatepicker#36]
Hi,

In the previous datepicker I could pass as dateFormat option the value `dd/mm`. In this package, we end up with errors.

`TypeError: Cannot read property 'value' of undefined`

Stackblitz to reproduce: https://stackblitz.com/edit/angular-9-1-0-angular-mydatepicker

**Comment by kekeh** [comment]
I fixed this issue. Install version **0.5.5**.
