### ISSUE TITLE
Year navigation buttons messed up with disabled years

### ISSUE THREAD

**Issue by fidian** [kekeh/angular-mydatepicker#4]
On the [demo page](https://kekeh.github.io/angular-mydatepicker/), select the option "Disable until yesterday". Open the calendar and go to the year selection. Click the right arrow to go forward in the list of years (first screenshot). On that list, try to navigate backwards and you'll see it is not allowed (second screenshot).

![Screenshot from 2019-06-06 10-50-39](https://user-images.githubusercontent.com/428348/59047212-0e92c280-8849-11e9-978b-d4bb3b2c27f6.png) ![Screenshot from 2019-06-06 10-50-09](https://user-images.githubusercontent.com/428348/59047216-10f51c80-8849-11e9-84ee-9bc8e69d2ca1.png)

The same issue shows up if you "Disable since tomorrow" and navigate backwards in the years.

**Comment by kekeh** [comment]
Thanks @fidian 

it is bug, but you can set the disableHeaderButtons option to false. I think then it should work.

**Comment by kekeh** [comment]
This is fixed in version 0.0.11.
