### ISSUE TITLE
changeDetection: ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by jamalsoueidan** [kekeh/angular-mydatepicker#42]
When adding this to my component, I'm getting this error:

```
changeDetection: ChangeDetectionStrategy.OnPush
```

ERROR TypeError: Cannot read property 'rtl' of undefined

**Comment by kekeh** [comment]
[Here](https://stackblitz.com/edit/angular-emptyproject-8-pipe-nxavs3?file=src%2Fapp%2Fcalendar.component.ts) is an example of
```
changeDetection: ChangeDetectionStrategy.OnPush
```

**Comment by kekeh** [comment]
Similar issue: https://github.com/kekeh/angular-mydatepicker/issues/13
