### ISSUE TITLE
Next months arrow disabled even having enabled date in next month in Inline mode. 

### ISSUE THREAD

**Issue by acharyaks90** [kekeh/angular-mydatepicker#44]
HI, 

Please look at stackblitz link for more clearance 
https://stackblitz.com/edit/mydatepicker-inline-disbale-issue
If after disabling the whole calendar using disableUntil and disableSince then
providing enabledDates array. makes next month selector disable even some dates are enabled for next month.

**Comment by kekeh** [comment]
Hi @acharyaks90 

I will check that but quick fix is set **disableHeaderButtons** option to **false**. Then the header arrows are not disabled in any case.

**Comment by kekeh** [comment]
I fixed this issue. You can try here: 

[stackblitz.com - angular-mydatepicker](https://stackblitz.com/edit/mydatepicker-inline-disbale-issue-kkvuuf)

After that install version **0.9.1** from npm.
