### ISSUE TITLE
Default value in reactive form

### ISSUE THREAD

**Issue by RonRofe** [kekeh/angular-mydatepicker#45]
How can I put a default value on reactive forms when the form initializes ?

**Comment by kekeh** [comment]
There is an [example](https://github.com/kekeh/angular-mydatepicker/wiki/reactive-forms-(bootstrap-4-and-font-awesome)) in wiki pages. Example app [example](https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-reactive-forms/date-picker-reactive-forms.ts#L25).

Both of those examples use **javascript date object** to initialize the date. It is also possible to initialize with the [IMyDate](https://github.com/kekeh/angular-mydatepicker/blob/master/projects/angular-mydatepicker/src/lib/interfaces/my-date.interface.ts) object.

Example to initialize with [IMyDate](https://github.com/kekeh/angular-mydatepicker/blob/master/projects/angular-mydatepicker/src/lib/interfaces/my-date.interface.ts) object.

```ts
ngOnInit() {
  // Initialize to yesterday date
  let d: Date = new Date();
  d.setDate(d.getDate() - 1);

  let model: IMyDateModel = {isRange: false, singleDate: {
     date: { year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate() }
  }};

  this.myForm = this.formBuilder.group({
    myDate: [model, Validators.required]
    // other controls are here...
  });
}

```
