### ISSUE TITLE
marker's

### ISSUE THREAD

**Issue by nt4solutions** [kekeh/angular-mydatepicker#46]
Can the day marker, or weekend markers, or holiday markers, be diferents, costumized  ?

**Comment by kekeh** [comment]
You can set separate (own) styles to each marked dates. Here is an example on how to do it: [usage of markDates option](https://github.com/kekeh/angular-mydatepicker/wiki/usage-of-markDates-option). Also check instructions of the **markDates** option from the [README](https://github.com/kekeh/angular-mydatepicker/blob/master/README.md#options-attribute).

Is this what you want?

**Comment by nt4solutions** [comment]
this can be applied on the same perspective on the disabled days

**Comment by kekeh** [comment]
You can set both marked and disabled dates to same calendar view. You can use **disableDates** option like **markedDates** option. [Here](https://github.com/kekeh/angular-mydatepicker/wiki/usage-of-disableDates-option) is an example of **disabledDates** option.
