### ISSUE TITLE
how i can reflect default value of date from input to datepicker?

### ISSUE THREAD

**Issue by gmengi** [kekeh/angular-mydatepicker#53]
After selecting the date from the date picker, it reflects the value in input but if I have a default value in input that is not reflecting into date picker.

**Comment by kekeh** [comment]
Type value to the input box. It must be in the same format that is given in **dateFormat** option.

Try here: https://kekeh.github.io/angular-mydatepicker/

The first date picker on the page. Type value **10.7.2020** into input box and the open calendar. Date **10.7.2020**  is selected on calendar.

**Comment by kekeh** [comment]
Use **ngModel** to set default date like below.
```html
  <input class="input-box" placeholder="Click to select a date" 
    angular-mydatepicker name="mydate" (click)="dp.toggleCalendar()" 
    [(ngModel)]="model" [options]="myDpOptions" 
    #dp="angular-mydatepicker" (dateChanged)="onDateChanged($event)"/>
```
```ts
this.model = {isRange: false, singleDate: {jsDate: new Date()}};
// or
this.model = {isRange: false, singleDate: {date: {year: 2020, month: 7, day: 10}}};
```

**Comment by gmengi** [comment]
What? if I'm using inline mode with input and bind value with ngModel?

**Comment by kekeh** [comment]
Set input type to hidden like here: https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-inline/date-picker-inline.html#L10

**Comment by kekeh** [comment]
On this https://kekeh.github.io/angular-mydatepicker/ page the inline datepicker uses input type of hidden.

Code: https://github.com/kekeh/angular-mydatepicker/blob/gh-pages/src/app/dp-inline/dp-inline.component.html#L5

**Comment by gmengi** [comment]
In this case, I don't want to hide input. because I want to populate the selected date or default date in input as well.
