### ISSUE TITLE
Panel overlay problem

### ISSUE THREAD

**Issue by nchetbani** [kekeh/angular-mydatepicker#54]
We have a problem with angular material, when we try to use the mydatepicker inside of the panel (AM) and the mydatepicker is on the end of panel, as showin below, we can't see the panel where we open the picker, because the panel of the angular material have a overflow: hidden.

Please, do you have solution for this problem? 
![myDatepicker-pb](https://user-images.githubusercontent.com/45500478/87330316-b5f82380-c538-11ea-94a3-76aadae00f68.png)

**Comment by kekeh** [comment]
Set option **appendSelectorToBody** to **true**. It works in my test.

Let me know if this option is working or not.

**Comment by nchetbani** [comment]
Thanks for your responsiveness 
The option is working but with this option the Datepicker panel is displayed on the left corner of the screen (x:0, y:0)

**Comment by kekeh** [comment]
Ok. Parent element of the **input** box have to be **position: relative** style like in [this](https://github.com/kekeh/angular-mydatepicker/wiki/Own-style-in-input-box-(no-bootstrap))  example. 

Can you check that?

**Comment by nchetbani** [comment]
it don't work

**Comment by kekeh** [comment]
Can you create demo to the [stackblitz](https://stackblitz.com/) or [plunker](https://plnkr.co/) from issue and I will check that?

Another way to solve the issue is override the panel style to **overflow: visible**.

**Comment by nchetbani** [comment]
ok, I'll do it
Let just check other case and come back to you

**Comment by nchetbani** [comment]
It work fine now!!  I forgot to settled some setup

Many thanks for your help
