### ISSUE TITLE
Can we have fix start date and allow only end date to change in date range?

### ISSUE THREAD

**Issue by rohanpadwalkar** [kekeh/angular-mydatepicker#59]
I have a scenario where i want to use date range. but start date has to be today and dont want user to change start date. he can only select end date in date range.

thanks in advance .

**Comment by kekeh** [comment]
Hi @rohanpadwalkar 

Your case is not possible with this component. 

Just add one date picker (not date range mode) to the selection of end date. No need to select start date because it is always today??? This come to my mind at first.
