### ISSUE TITLE
Navigation on month selection screen behaves oddly.

### ISSUE THREAD

**Issue by fidian** [kekeh/angular-mydatepicker#6]
First, I want to say how much I appreciate the time you have put into this module. It's better than what I was hoping to find and also better than what I had almost resolved to write. Thank you!

When viewing a calendar (the "day" type of view), the navigation buttons in the upper right and left will change the month. When viewing the list of years, the navigation buttons jump to the next page of years. Both of these are consistent with what I would expect since the navigation buttons allow you to make large jumps in relation to what's being viewed.

The month view is odd. Navigating left or right only switches a single month instead of going to the next or previous year.

Additionally, I found another bug. If you disable all of the previous months ("Disable until yesterday") and press the right button several times to get into 2020, the list of months doesn't update. "Jan" stays unavailable even though the top of the calendar reads "Dec 2020".

Maybe both of these could be fixed at the same time by having those navigation buttons switch years and then repaint the list of months?

**Comment by kekeh** [comment]
Thanks @fidian 

Good findings :-) In the second bug what do you mean by "list of months doesn't update"?

**Comment by fidian** [comment]
This didn't capture the mouse, but you should be able to see what I did on the demo page. I selected one option, pulled up the great calendar, clicked on the month, then rapidly clicked on the ">" to advance the calendar well into the future. The months that are disabled when the month selection view opens all remain disabled even though I've supposedly advanced quite a bit.

![ezgif com-crop](https://user-images.githubusercontent.com/428348/59215083-fb039680-8b7d-11e9-99fc-34d24dbafc30.gif)

**Comment by kekeh** [comment]
Fixed in version **0.0.12**.
