### ISSUE TITLE
Change the dash character in the range date picker

### ISSUE THREAD

**Issue by dogandipcin** [kekeh/angular-mydatepicker#62]
Can we possibly change the dash character in the range date picker?
<img width="339" alt="Screen Shot 2020-09-22 at 10 19 42" src="https://user-images.githubusercontent.com/25384861/93853852-497a6d00-fcbd-11ea-9446-ac23260165e6.png">

**Comment by kekeh** [comment]
Hello @dogandipcin 

Yes you can. There is option **dateRangeDatesDelimiter**.
