### ISSUE TITLE
reactive forms with date range example

### ISSUE THREAD

**Issue by dileepbalineni** [kekeh/angular-mydatepicker#65]
Can anyone  please provide the reactive forms (bootstrap 4 and font awesome) date range example

**Comment by kekeh** [comment]
Hi @dileepbalineni 

Example app: https://github.com/kekeh/angular-mydatepicker/tree/master/example/app/date-picker-reactive-forms

**Comment by kekeh** [comment]
Run example app by following instructions from here: https://github.com/kekeh/angular-mydatepicker#development-of-this-component
