### ISSUE TITLE
Bug when initializing a disabled datepicker

### ISSUE THREAD

**Issue by skaireka** [kekeh/angular-mydatepicker#68]
If a datepicker is initialized with a value when it's not disabled - everything works fine.
If a datepicker is initialized with a value and set as disabled - date doesn't show in the input and instead placeholder is shown.

Stackblitz example:
https://stackblitz.com/edit/angular-9-1-0-angular-mydatepicker-ygezxo
The only difference between the inputs is one is [disabled]="isDisabled" the other [disabled]="!isDisabled"

I haven't actually found a disabled property in the docs, so I'm wondering if I missed something or if this is a bug?

**Comment by kekeh** [comment]
Hello @skaireka 

Here is working version: https://stackblitz.com/edit/angular-9-1-0-angular-mydatepicker-vmoc3v?file=src%2Fapp%2Fchild%2Fchild.component.html

You can define the disable attribute this way: **[attr.disabled]="isDisabled"** then it is working.

**Comment by kekeh** [comment]
You can do: [attr.disabled]="isDisabled ? '' : null"

**Comment by skaireka** [comment]
That works, thank you!
