### ISSUE TITLE
Limit date range selection in date range picker

### ISSUE THREAD

**Issue by abhishekpatel1234** [kekeh/angular-mydatepicker#69]
Is there any option in angular-mydate range picker to restrict the date range to, say 7 days ?
I want to prevent the user from giving a date range of more than 7 days using the date range model. 
I am finding no specific way to call the disableSince () function after selecting only the "start date" in the Date Range Picker so that we can dynamically disable all dates after start date+7 days

**Comment by kekeh** [comment]
After you have selected start date you can set **disableSince** option dynamically from start date + 7 days. 

Actually I don't know what you are trying to do, but there are many options to disable dates.

**Comment by abhishekpatel1234** [comment]
Thanks for the quick response :-)
But not being able to find any callback function to call/set **disableSince** option dynamically from start date + 7 days **after selection of the start date**. 
The Datechanged call back is being called only after both the start and end date is being selected. 
 I want to prevent the user from giving a date range of more than 7 days (from the start date selected) using the date range model.

**Comment by kekeh** [comment]
I haven't test the code below, but it might work.

```html
<input angular-mydatepicker [(ngModel)]="model" [options]="myDatePickerOptions" 
    #dp="angular-mydatepicker" (rangeDateSelection)="onRangeDateSelection($event)"/>
```

```ts
import {IAngularMyDpOptions, IMyRangeDateSelection} from 'angular-mydatepicker';

export class MyApp {
    myDatePickerOptions: IAngularMyDpOptions = {
        dateRange: true,
        disableSince: {year: 0, month: 0, day: 0}
    }

    constructor() {}

    onRangeDateSelection(event: IMyRangeDateSelection): void {
        console.log('onRangeDateSelection(): event: ', event);

        let {isBegin, date} = event;

        let options: IAngularMyDpOptions = getCopyOfOptions();
        if(isBegin) {
            let d = new Date(date.year, date.month - 1, date.day);
            d.setDate(d.getDate() + 7);
            
            options.disableSince = {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
            this.myDatePickerOptions = options;
        }
        else {
            // end date selection - remove disableSince option
            options.disableSince = {year: 0, month: 0, day: 0)};
            this.myDatePickerOptions = options;
        }
    }

    // get copy of options
    getCopyOfOptions(): IAngularMyDpOptions {
        return JSON.parse(JSON.stringify(this.myDatePickerOptions));
    }
}
```

**Comment by abhishekpatel1234** [comment]
Thanks keheh. 
But (onRangeDateSelection) made me loose the main functionality of choosing a date range :(. I am no longer being able to choose the "end date"

Selecting the "begin date" , is triggering the callback function (onRangeDateSelection) which is indeed disabling all dates after 7 days. (your sample code worked as charm there ! :))
But after that I am not being able to select the "end date". As soon as I am trying to select the "end date", that is being again considered as the new "begin date".
Attached is the screenshot which might give you a better idea. I selected 2nd Dec as "begin date" and moment I tried selected 4th Dec as "end date" ( that became the new "Begin Date") and callback function (onRangeDateSelection) was again called, and all future dates were greyed out 7 days after 4th Dec (instead of 7 days after 2nd Dec)

Also if I go back in the past, and select a begin date, the execution of the callback function "onRangeDateSelection", is bringing me to the current month, and I have to go back to the old month to select the end date ( which anyway I am not being able to)

Any help will be highly appreciated.

![DateRangePicker](https://user-images.githubusercontent.com/75262357/100926808-e76b8e80-34db-11eb-886f-1318ecb1a2a5.png)

**Comment by heaven-dev** [comment]
Hi @abhishekpatel1234 

The code below works. At first install the latest  version of the component **0.10.3**. Code is in example application [here](https://github.com/kekeh/angular-mydatepicker/blob/master/example/app/date-picker-ngmodel/date-picker-ngmodel.ts#L1065) but it is commented out. You can [run](https://github.com/kekeh/angular-mydatepicker#development-of-this-component) test application. It is the first date picker on the page. At first select **Date range** checkbox.

![demo](https://user-images.githubusercontent.com/68559229/100986745-4968da00-3556-11eb-9e9a-24468b689c83.gif)

```html
<input angular-mydatepicker [(ngModel)]="model" [options]="myDatePickerOptions" 
    #dp="angular-mydatepicker" (rangeDateSelection)="onRangeDateSelection($event)"/>
```

```ts
@ViewChild('dp') ngxdp: AngularMyDatePickerDirective;
...
  onRangeDateSelection(event: IMyRangeDateSelection): void {
    console.log('onRangeDateSelection(): event: ', event);

    let {isBegin, date, jsDate} = event;

    let options: IAngularMyDpOptions = this.getCopyOfOptions();
    if(isBegin) {
        // start date selection - set disable since (selected date + 7 days)
        this.ngxdp.writeValue({
          isRange: true, 
          singleDate: null, 
          dateRange: {
            beginDate: {year: 0, month: 0, day: 0},
            endDate: {year: 0, month: 0, day: 0}
          }
        });

        this.ngxdp.setHostValue("");

        let d = new Date(jsDate.getTime());
        d.setDate(d.getDate() + 7);
        
        options.disableSince = {year: d.getFullYear(), month: d.getMonth() + 1, day: d.getDate()};
        this.myDatePickerOptions = options;

        this.defMonth = {
          defMonth: date.month + '.' + date.year,
          overrideSelection: true
        };
    }
    else {
        // end date selection - remove disableSince option
        options.disableSince = {year: 0, month: 0, day: 0};
        this.myDatePickerOptions = options;

        let d: Date = new Date();

        let month: any = d.getMonth() + 1;
        if (month < 10) {
          month = '0' + month;
        }

        this.defMonth = {
          defMonth: month + '.' + d.getFullYear(),
          overrideSelection: false
        };
    }
  }
```

**Comment by abhishekpatel1234** [comment]
hello kekeh and Dev !!Everything is working almost perfect !!...Except I am not being able to keep the calendar pop up stick to the  month of selection. If I am going back in past and selecting the begin date in the month of November, as soon as the code,  reaches the below line, the calendar pop up view automatically  shifts to the current month (December) and I need to again click and go back to the month of November, to give the end date,
**this.defMonth = {
          defMonth: date.month + '.' + date.year,
          overrideSelection: true
        };**

I did a console.log of **this.defMonth** as well and it gives the below expected result, still somehow the month goes to the current month (December)
defMonth{"defMonth":"11.2020","overrideSelection":true}

**Comment by kekeh** [comment]
As you can see the video above it is working fine. I was able to select November and October dates without problems. You have to share code otherwise it is difficult to say what is the problem.

Create demo from your code (datepicker part) here: https://stackblitz.com/ You can implement the demo step by step to see when it starts to fail. At first implement only the **rangeDateSelection** callback if you are using other callbacks..

If you are able to reproduce the issue on **stackblitz** add demo link to this issue.

**Comment by abhishekpatel1234** [comment]
Kekeh and Dev...Thanks a million !!!!. It is working perfectly. Missed one option so..
