### ISSUE TITLE
How to set date in datepicker input-field

### ISSUE THREAD

**Issue by joshi-anshul** [kekeh/angular-mydatepicker#70]
Hello @kekeh 

Date picker works very good, but I have a silly question :(

How can I set default date in date picker input field?

Thanks

**Comment by kekeh** [comment]
Hello @joshi-anshul 

You have to use **ngModel** to set initial date. Set javascript date object or mydate object to **ngModel**. Here is an example: https://github.com/kekeh/angular-mydatepicker/wiki/initialize-date-model-(single-date-mode)

Check the ngOnInit() method. It shows both of above methods.

**Comment by joshi-anshul** [comment]
@kekeh thanks a lot
