### ISSUE TITLE
angular v10 > v11 migration failure

### ISSUE THREAD

**Issue by krogan** [kekeh/angular-mydatepicker#76]
when migrating my angular-cli v10 app to v11, the migration immediately fails with a compatibility error.
 
had to force the upgrade/migration, but still unsure of any unexpected behaviour at build or runtime

Fetching dependency metadata from registry...
                  Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "11.2.1").
                  Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0" (extended), would install "11.2.1").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\somebody\AppData\Local\Temp\ng-IoB5fP\angular-errors.log" for further details.

error log file contents:

[error] Error: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
    at _validateUpdatePackages (C:\Users\somebody\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@schematics\update\update\index.js:158:15)
    at C:\Users\somebody\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@schematics\update\update\index.js:675:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

on running the migration again with a force....
ng update @angular/cli @angular/core --force

Using package manager: 'npm'
Collecting installed dependencies...
Found 40 dependencies.
Fetching dependency metadata from registry...
                  Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0" (extended), would install "11.2.1").
                  Package "angular-mydatepicker" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0" (extended), would install "11.2.1").
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1102.1" (was "0.1001.3")...
    Updating package.json with dependency @angular/cli @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/compiler-cli @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/language-service @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency zone.js @ "0.11.4" (was "0.11.1")...
    Updating package.json with dependency @angular/animations @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/common @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/compiler @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/core @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/forms @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/platform-browser @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "11.2.1" (was "10.1.3")...
    Updating package.json with dependency @angular/router @ "11.2.1" (was "10.1.3")...
  UPDATE package.json (1724 bytes)
√ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

**Comment by kekeh** [comment]
Hello @krogan 

I removed peer dependencies from the component. Try to install the latest version **0.11.0**.

I tested installation and functionality of the component with Angular 6, 7, 8, 9, 10 and 11. Component worked ok with those Angular versions.

**Comment by krogan** [comment]
thank you.. retested and all works great!
