### ISSUE TITLE
disabled dates behavior (year / month selector)

### ISSUE THREAD

**Issue by m-poh** [kekeh/angular-mydatepicker#77]
Hello @kekeh 

There is a scenario with disabled dates which might make use of a configurable option. The scenario:

* currentDate = 2020-06-01
* minDate = 2018-06-02
* no date selected in datepicker yet
* trying to select 2018-06-03
* going to year selector
* year 2018 disabled

What could be configurable: whether the disabled years / months are selectable

(the following paragraph was a thought process about a more strict solution, where year 2018 and month 06 would be enabled, but 0-2017 / 2018-05 would be disabled)
i've thought about a number of different scenarios of either minDate variants or single days disabled. for minDate variant a some kind of a partial check of disabled / enabled in the given range could qualify as a solution to this, but when taking into account single disabled days, then a solution of this kind is again not enough.

a second approach that would be general enough and would offer some kind of a solution is something similar to the current disableHeaderButtons: false. The same functionality, but for the year / month selection buttons. This way the year 2018 button would be enabled (but colored), and you would be able to easily reach 2018-06-03. The "no date selected" was just a case chosen to demonstrate the maximum level of possible confusion from an user, but of course this applies to a selected date (in the proper manner) as well.

**Comment by kekeh** [comment]
Hello @m-poh 

Try to use **minYear**, **maxYear** and **disableDateRanges** options to disable dates like below. You can also enable already disabled dates by **enableDates** option if you want to enable single dates.
```ts
    myDatePickerOptions: IAngularMyDpOptions = {
        dateFormat: 'dd.mm.yyyy',
        dateRange: false,
        minYear: 2010,
        maxYear: 2037,
        disableDateRanges: [{
            begin: {year: 2010, month: 1, day: 1}, 
            end: {year: 2018, month: 6, day: 1}
        },
        {
            begin: {year: 2017, month: 1, day: 1}, 
            end: {year: 2018, month: 5, day: 31}
        }],
        enableDates: [{year: 2010, month: 6, day: 15}, {year: 2010, month: 6, day: 16}]

        // other options here
    }
```

**Comment by m-poh** [comment]
Yes, i am using disableUntil atm. I will give your suggestions a quick spin.

**Comment by m-poh** [comment]
aah, but actually what i'm seeing in your suggestion is that the disableDateRanges ends at 2018-06-01, but my example had the end at 2018-06-02. That is exactly what is causing the issue, that i'd need 2018-06-02 to be disabled, but i'm trying to reach 2018-06-03.

**Comment by m-poh** [comment]
Alright thanks, this along with a proper min / max year covers the cases mostly. The only asterisk is that all of months are in the enabled style, but this is not that big of an issue.
