### ISSUE TITLE
Date & Month defaulting to current month and Date

### ISSUE THREAD

**Issue by nagasudhakarch** [kekeh/angular-mydatepicker#79]
in any of the Date formats if the date & months entered as ZEROs, the date & month defaulting to current.
For ex- 

1. date format is dd.mm.yyyy
2. entered date as 00.00.2010.
3. date automatically changing to 10.04.2010 on leaving the field (month & dates are defaulted to current month and date).  

Issue is happening here (https://kekeh.github.io/angular-mydatepicker/) also.

**Comment by kekeh** [comment]
Hello @nagasudhakarch 

Try to set the **inputFieldValidation** option to **false**.

**Comment by nagasudhakarch** [comment]
Hi kekeh,
I tried that option but no luck.
With inputFieldValidation option in the input field it is showing 00.00.2010 only. But the control value is getting changed to 04.11.2010.
Please check sample at - https://stackblitz.com/edit/angular-puxw3k?file=src%2Fapp%2Fapp.component.html

**Comment by kekeh** [comment]
Hello @nagasudhakarch 

I fixed the bug: https://github.com/kekeh/angular-mydatepicker/commit/6c9a2cc9fe0907d867fa72d39fd195f7217bf1b8

Install new version of the component: **0.11.1**.

Try fixed version here: https://stackblitz.com/edit/angular-4s6yat?file=src%2Fapp%2Fapp.component.ts

Now you can keep value of **inputFieldValidation**. It can be **true** (default).

**Comment by kekeh** [comment]
Hello @nagasudhakarch 

I fixed the bug. Install new version of the component: **0.11.2**.

Try fixed version here: https://stackblitz.com/edit/angular-2oljde?file=src%2Fapp%2Fapp.component.ts

Now you can keep default value of **inputFieldValidation**.

**Comment by nagasudhakarch** [comment]
Hi Kekeh,
The fix is working fine. Thank you for the fix.
But I found one more issue, if I make the inputFieldValidation option false and enter date manually dateChanged event not getting triggered even for valid Date.

Thanks,
Sudhakar

**Comment by kekeh** [comment]
If you want that **dateChanged** is triggered on **blur** event of input box you have to set **inputFieldValidation** to true.
