### ISSUE TITLE
`position: relative` can mess up the layout

### ISSUE THREAD

**Issue by fidian** [kekeh/angular-mydatepicker#8]
I have a fairly broad CSS reset/normalize/what-have-you that contains the following rule.

```
* {
    position: relative
}
```

This really helps when we want to absolutely position elements. However, this breaks with angular-datepicker. Specifically, `<lib-angular-mydatepicker-calendar>` needs to be `position: static`, otherwise the calendar drop-down doesn't align correctly. I think the best fix is to use `HostBinding('style.position') position = 'static'` or something similar in the component to ensure that this always has a working value.

Additionally, the `.ng-mydp` class should have `position: static`.

**Comment by kekeh** [comment]
Thanks, I have fixed it in version 0.1.3.
