### ISSUE TITLE
Custom Date format announced by screen readers (NVDA)

### ISSUE THREAD

**Issue by ColemanTO** [kekeh/angular-mydatepicker#82]
Hi Keke,

I'm using the angular-mydatepicker on a project and was wondering if there is an API for customizing the text read by screen readers. There is an HTML5 semantic date control (input type="date") that, at least in Chrome, announces the selected date in a more user-friendly manner. It also provides a spin button for changing the date with the up/dn arrow keys. Is this something I could easily customize?

For reference: 
![Screenshot 2021-05-13 061739](https://user-images.githubusercontent.com/2119454/118118790-05a2b800-b3b3-11eb-9942-2047ae77cd74.png)
<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date>

Thanks,
Tom

**Comment by kekeh** [comment]
Hello Tom

I haven't tested the date picker with input field type **date**. I have used only input field type **text**. It seems that Chrome and Firefox opens a browser specific date picker if the input field type is set to **date**.

I think you cannot use the input field type **date** if you use angular-mydatepicker.

**Comment by ColemanTO** [comment]
Hi Keke,

I just shared the date input for comparison - what I really want is to customize the way that the screen reader (NVDA) announces the date. Is there an API for it? The spin button on the month/day/year would be nice too.

**Comment by kekeh** [comment]
Hi Tom

Do you want to add the **aria-label** attribute to the **input** box of datepicker? 

If so you can use the [dateChanged](https://github.com/kekeh/angular-mydatepicker#datechanged-callback) callback. It is also possible to implement with the [rangeDateSelection](https://github.com/kekeh/angular-mydatepicker#rangedateselection-callback) callback.

Implement one of the above callback and add **aria-labe**l attribute to the element.

**Comment by kekeh** [comment]
Example of **dateChanged** callback: https://github.com/kekeh/angular-mydatepicker/wiki/dateChanged-callback

**Comment by kekeh** [comment]
You can test the **dateChanged** callback here: https://kekeh.github.io/angular-mydatepicker/

At first open console of the browser and select **Date range picker** checkbox and after that select date range from the datepicker. You can see result of the **dateChanged** callback call on the console of the browser.

**Comment by ColemanTO** [comment]
Awesome - thanks!
