### ISSUE TITLE
Disable Until Month Repaint

### ISSUE THREAD

**Issue by GusK7** [kekeh/angular-mydatepicker#86]
I Am using    "angular-mydatepicker": "^0.11.3", with     "@angular/cli": "^9.0.4",

I have two instances of calendar for a booking component. When I select a date from next month from the current the second instance disables the dates of the of first calendar selection but month does not getting updated to next month.

  onDateChanged(event: IMyDateModel) {
    const d: Date = new Date(event.singleDate.jsDate);
    d.setDate(d.getDate());
    const copy1: IAngularMyDpOptions = this.getCopyOfOptions1();
    copy1.disableUntil = {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    };
    this.myOptions2 = copy1;
    const copy2: IAngularMyDpOptions = this.getCopyOfOptions2();
    copy2.disableUntil = {
      year: d.getFullYear(),
      month: d.getMonth() + 1,
      day: d.getDate()
    };
    this.myOptions1 = copy2;

 }

![image](https://user-images.githubusercontent.com/12913638/119828387-1c273400-bec8-11eb-9e09-344ce6585e8f.png)

**Comment by kekeh** [comment]
Also if you need to select a start and end date you can set the datepicker to date range mode and use only one datepicker (date range picker).

**Comment by GusK7** [comment]
Thanks a bunch for the fast reply defaultMonth work like a charm.

I would suggest putting this into your documentation for two instances of the calendar. I did some search before posting here and I seen a few posts asking about this issue.

Again, thanks alot.
