### ISSUE TITLE
No option for opening selector on input click

### ISSUE THREAD

**Issue by mvorisek7** [kekeh/angular-mydatepicker#9]
Looks like in the older version of this library, there was an option 'openSelectorOnInputClick' which would open the calendar when the input was clicked, but I don't see the option anymore in this library. Just wondering if there were plans to add it back in. Thanks

**Comment by kekeh** [comment]
Here is demo. The third date picker: https://kekeh.github.io/angular-mydatepicker/

It is done this way: https://github.com/kekeh/angular-mydatepicker/blob/gh-pages/src/app/no-bootstrap/no-bootstrap.component.html

**Comment by mvorisek7** [comment]
Ah didn't even think about adding the open function to the click event, Duh. Thanks!
