### ISSUE TITLE
How to open the Calendar only when calendar icon is pressed

### ISSUE THREAD

**Issue by aslam-angular-dev** [kekeh/angular-mydatepicker#92]
`<input  angular-mydatepicker name="mydateFrom"id="customFromDate"
                        style="cursor: pointer;"  (click)="dpFrom.toggleCalendar()"
                     [options]="myDpOptionsFrom" #dpFrom="angular-mydatepicker"
                        (dateChanged)="onDateFromChanged($event)">`
     I do used the datepicker like this,how do I open the calendar only when the calendar icon is clicked and not when input is clicked?

How to achieve this?

**Comment by kekeh** [comment]
Example below uses **button** element, but you can use the same method also with the icon.

```html
<input angular-mydatepicker name="mydate" [(ngModel)]="model" 
    [options]="myOptions" #dp="angular-mydatepicker"/>

<button type="button" (click)="toggleCalendar()">Toggle</button>
```

```ts
import {AngularMyDatePickerDirective, 
        IAngularMyDpOptions, 
        IMyDateModel} from 'angular-mydatepicker';

export class MyApp {
    @ViewChild('dp') mydp: AngularMyDatePickerDirective;

    myOptions: IAngularMyDpOptions = {
        // options here...
    }

    model: IMyDateModel = null;

    constructor() {}

    // call the toggleCalendar() function of the directive
    toggleCalendar(): void {
        this.mydp.toggleCalendar();
    }
}
```
