### ISSUE TITLE
dateFormat not respected when options set in dateChanged callback

### ISSUE THREAD

**Issue by huffSamuel** [kekeh/angular-mydatepicker#93]
## Description
I'm attempting to have the datepicker display the date ordinal as a day of the month rather than the entire date, for instance "3rd of the month" or "16th of the month". In the `dateChanged` callback I calculate the ordinal, create a new dateFormat, and copy the current options and reassign with the new date format. Sometimes this date format is respected immediately, sometimes the format lags one selection behind the current date.

## Steps to Reproduce
See my source code [here](https://github.com/huffSamuel/dp-example). Snippets below:

home.page.ts
```ts
...
options: IAngularMyDpOptions;
onDateChanged(event: IMyDateModel) {
  const date = event.singleDate.day;
  const copy = JSON.parse(JSON.stringify(this.options));
  copy.dateFormat = this.getDateFormat(date); // Returns 'd' + the ordinal ('st', 'nd', 'rd', th')
  this.options = copy;
}
...
``` 

home.page.html
```html
...
    <input angular-mydatepicker #dp="angular-mydatepicker" [(ngModel)]="model" (dateChanged)="onDateChanged($event)" [options]="options"/>
...
```

1. Open the calendar
2. Select a date
3. Select a date that ends in a different ordinal (1st, 2nd, 3rd, 4th, etc)
4. Observe the ordinal lags behind the date

I can more reliably set the ordinal by updating the options, then updating the bound model in a `setTimeout`, but that isn't always effective.

## Expected Results
- Updating options uses the new dateFormat.
- Text field is updated and text reflects the dateFormat.

**Comment by kekeh** [comment]
I added this kind of feature to the component. Install newest version of the component from npm (0.11.5).

In the **dateFormat** option you can define ordinal dates (d##) for example
```ts
dateFormat: 'd## of mmm yyyy'
```

**Comment by huffSamuel** [comment]
Works perfectly. Thank you!
