### ISSUE TITLE
ariaLabelInputField is No Longer Found in IMyOptions

### ISSUE THREAD

**Issue by beneccles** [kekeh/angular-mydatepicker#94]
I am updating a project to use angular-mydatepicker instead of mydatepicker, and I noticed that ariaLabelInputField is no longer found inside of the IMyOptions. Did anything supersede it? I have several datePickerConfigs that use it.

**Comment by kekeh** [comment]
Input box is your own code. You can add arialabel to it easily for example:

```html
<input angular-mydatepicker [(ngModel)]="model" [options]="myDatePickerOptions" 
    #dp="angular-mydatepicker" aria-label="Date input field" />
```

```ts
import {IAngularMyDpOptions, IMyDateModel} from 'angular-mydatepicker';

export class MyApp {
    myDatePickerOptions: IAngularMyDpOptions = {
        // options here...
    }

    constructor() {}
}
```
