### ISSUE TITLE
6 date rows shown in date view

### ISSUE THREAD

**Issue by gopinath619** [kekeh/angular-mydatepicker#95]
Hi @kekeh, 
Thanks for the wonderful work done so far. You saved my day with the date range picker for my angular 7 version project.

There was one minor suggestion from my side regarding the date view. Currently the date view are showing in 6 rows. As it is still disabled, it may take some extra height for inline view. 

Is there any possibility to hide the last row ? please suggest any solution or work around.

![Datepicker_inline_6_rows](https://user-images.githubusercontent.com/34092238/133746700-3bff17d2-82d6-4d13-bee4-3534b3b087b4.jpg)

**Comment by kekeh** [comment]
In the image above the last row is not disabled. You can select the date also from that row.

If you want you can change style of the row. Example on how to change the style of the date picker: https://github.com/kekeh/angular-mydatepicker/wiki/color-theme-(grey)

CSS classes of those dates are **myDpPrevMonth** and **myDpNextMonth**.

Test here the inline date picker: https://kekeh.github.io/angular-mydatepicker/ At first open the console of the browser to see **dateChanged** callback call.

**Comment by gopinath619** [comment]
Thank you @kekeh for instant reply and I got the solution and customized the datepicker according to my requirement.
