### ISSUE TITLE
angular-mydatepicker doesnot popup properly when there are multiple forms

### ISSUE THREAD

**Issue by hemanth281** [kekeh/angular-mydatepicker#98]
Hi @kekeh
When there are multiple forms in the screen, like one form after the other( shown in Issue1 image) and if there is calendar in one of the forms and when we click on the calendar button, the angular-mydatepicker calendar pops out but occupies all over the form and you can only see the calendar but not complete calendar and makes disappears all the content/labels in the form.

  I don't see an option to force the mydatepicker to pop out. I reviewed documentation and could not find. 

With ngx-mydatepicker this was never an issue, it always pop out from the form. 

**Code:**
<lib-angular-mydatepicker-calendar style="position: static;"><span></span><div class="ng-mydp ">
<div class="myDpSelector myDpSelectorArrow myDpSelectorArrowLeft myDpSelectorAbsolute" tabindex="0" ng-reflect-klass="myDpSelector" ng-reflect-ng-class="[object Object]" ng-reflect-lib-angular-my-date-picker-calendar="[object Object]" style="height: 266px; width: 266px; top: 43px; left: 0px;">
</div>
</lib-angular-mydatepicker-calendar>

**Comment by kekeh** [comment]
You can try to set option **appendSelectorToBody** to **true**. Can you use console of the browser to check that is there any global styles causing the issue.

Difficult to say anything without seeing code. If you have extra time can you create demo here https://stackblitz.com/ about the issue.

**Comment by hemanth281** [comment]
Thank you very much @kekeh. It resolved the issue.
